### PR TITLE
Added message component support

### PR DESCRIPTION
**Pull request by SjogrenDev**
-Added support for message components.
-Updated deprecated channelTypes
-Messages owned by the client user are now sent as the client user 
-Fixed the bug in LoadMessages function

### CODE REVIEW

**Comment by jleeson** [comment]
Thanks for working on this @SjogrenDev, I do have a question though, why are you deciding to store the old message id in the backup now? Additionally what is the purpose of adding the `messagesPerChannel` property? I would imagine it would be better to just derive the value off of the number of actually saved messages in a channel rather than assume every channel has the maximum which is already provided through the options anyway.

**Comment by SjogrenDev** [comment]
Hi,

I've added the old message id storing because with Discord bots we often work with channel ids and message ids, so the old id might be needed. Additionally, the project currently stores old channel ids, so it's a good practice to do it for messages too.

I've added the messagesPerChannel property because currently there's no way to check how many messages per channel are saved on an existing backup and we need that number for the backup load function.

**Comment by jleeson** [comment]
messagesPerChannel does not appear to be used in the backup load function, do you mean you are using that to pass to the option maxMessagesPerChannel yourself?

**Comment by SjogrenDev** [comment]
> messagesPerChannel does not appear to be used in the backup load function, do you mean you are using that to pass to the option maxMessagesPerChannel yourself?

Yeah, currently we cannot know how many messages per channel were saved on a backup, thus why I added it, so we can pass the number or lower in maxMessagesPerChannel in the backup load function

**Pull request merged**
