### PR TITLE
Several fixes, improvements and new features

### PR DESCRIPTION
**Pull request by Weeeqt**
**Fixes**
- Import ChannelType which is used in loadAfk()
- __dirname problem in ES modules
- Typo user.avatarUrl() -> user.avatarURL() in getMembers()
- Make sure we fetch all members in getMembers()

**New features**
- Backup and restore system channel (with flags)
- Backup and restore server boost progress bar
- Backup and restore auto moderation rules (including channels and roles)
- Reassign roles to members if they are invited
- Split restoration process into multiple stages: some stages must be synced and complete in certain order
- New load() option `doNotLoad`: 'main', 'roleAssignments', 'emojis'
- Updated typescript types

### CODE REVIEW

**Comment by jleeson** [comment]
Hey @Weeeqt, Thanks for creating this PR. Ill try and go through all the new features so this can be merged quickly. I have a couple questions regarding the bug fixes though.

1. Regarding the __dirname fix, what exactly was the issue with it in ES modules? Does this fix really require changing the minimum supported node version?

2. Regarding the change in the `getMembers()` function, rather than fetch them and then loop over the cached members, would there be any downside to just iterating through the returned members array directly?

3. If the members need to be fetched in the `getMembers()` function, should this also be done in the other resource functions such as `getRoles()` and `getEmojis()`

**Comment by Weeeqt** [comment]
@jleeson thank you for quick reply.

1. From what I learned ES `__dirname`, `__filename` etc are not defined in ES module. A "fix" is to use `import.meta.url`, but I think it wasn't added in es2015, at least I got error with it. Probably lower version can be used rather than es2022.
2. You are right, returned members collection should be fine. I overlooked this. In fact, if cache has max limit then we can lose some data and fetched result is preferable.
3. After conducting tests with members, I can confirm that if we rely solely on the cache without fetching all members, we will only back up those members that were cached up until that point. Not sure about roles, emojis and other resources. I assume it has similar problem, but it's tricky to test, because there are not that many roles or emojis as there are members.

**Comment by jleeson** [comment]
Looks like your correct about the __dirname problem with es modules, I did some testing and looks like we can keep the minimum node version at 16 by changing the esbuild target to "node16". 

When it comes to the change for members, I think its best each resource is fetched and iterated over rather than operating strictly from a cache. Just in case something happens to not be in cache, we can make sure an incomplete backup is not created by mistake.

I can quickly make these changes after merging in your PR if needed. I know this package does not have any formal tests but regarding the new features you have implemented, have you ensured they work as expected?

Once I have time to review each feature and everything checks out, I will get this merged and released.

**Comment by Weeeqt** [comment]
Yeah, seems like import.meta was added in es2020 and node16 aligns with es2021, so it should be fine I guess.

You are right, it's better to ensure we don't have incomplete backup.

Regarding testing these features - I've been running the bot with my changes for about 2 weeks now, made several backups with it and tested backup and restoration process yesterday, right before making this PR.
In actual PR I had to make some changes, to fit your options style and few other things. For example, initially, instead of `doNotLoad` option I added `actionType` option with `RestoreActionType` enum to choose what exactly to restore:
- Main backup part
- Emojis
This is because uploading too much emojis can get you rate limited fast and it would cause problems while trying to restore it.
Also, although usually I work with typescript, this time my project is in js, so I didn't need ts types, but I updated them, excluding stuff which is used internally, things like `roleMap` and `channelMap`.

Now regarding `roleMap`, `channelMap` and `oldId`. In short - this is so we can properly assign channels and roles not based on the name (which can't be unique), but on original id.
- First of all we include `oldId` where it's needed in the backup.
- Then, when we restore roles and channels - we fill special maps, which tie `oldId` to new `Role` or `Channel`.
- And finally when we assign roles or restore auto moderation rules - we actually use proper roles and channels in them, not just channels with the same name.
I tested this part a lot to make sure it works. Downside is that these features require running backup load process in particular sequential order. We must ensure that roles and channels are created before autoModRules and role assignment process.
Although few things can run in parallel, because they don't depend on each other. Perhaps there is more sophisticated way to achieve this.
Also I must admit that I didn't change other parts of your code to this method. For example, channel permissions restore is still based on role name rather than id match. Probably `loadCategory` and `loadChannel` should utilize this trick as well, as well as other parts, such as: `loadAfk`, `loadEmbedChannel` and even System Channel in `loadFinalSettings` from this PR. Maybe I missed something besides these.

I noticed that load process happens in a bit uncontrolled manner, out of order, so I had to change it. We need roles restored first, then categories and channels with their permissions, then everything else.

**Comment by Weeeqt** [comment]
Oh, and regarding role assignment - I thought it would be nice to be able to run this stage separately. For example:
- We create new guild and perform main stage of backup restore.
- We give it some time for users to join the guild and/or use another bot to pull them.
- Then we assign roles to those who joined.

However, to achieve this as separate standalone stage we would have to choose:
- Either identify roles by name, like in your original code. Then it is truly standalone and doesn't depend on any other stage.
- Or store state (roleMap, channelMap, etc) in a file/db. Then it still requires main stage to be performed first, but we can do it any time and restart the bot in between, if necessary.
- Or we could require roleMap as parameter to this function. And library user can decide how to handle it. For example make a bot which asks to map new roles with old ones by selecting them manually in Role Picker interaction. Or provide a hardcoded map.

**Comment by jleeson** [comment]
I appreciate the thorough explanation, i think your right where applicable it may be best to switch to using an Id if discord itself allows repeatable names. It may be best to rethink these processes later on for a new major version and break compatibility with the original discord-backup package.

Ill finish going through the new code and get this merged. I appreciate the work you put in on this!

**Comment by jleeson** [comment]
@Weeeqt, I merged this In. I also went ahead and tested some of the new features and they work perfectly. Great work!

**Pull request merged**
