### PR TITLE
Added Promise to Backup.load

### PR DESCRIPTION
**Pull request by Phyroks**
Added possibility to use .then for backup.load

### CODE REVIEW

**Comment by jleeson** [comment]
@Phyroks Is there any reason why your unable to use .then with the current version? the load function is async and as such returns a promise thus enabling the use of async/await as well as .then and .catch. The code change you are suggesting is functionally equivalent to the existing version.

**Comment by Phyroks** [comment]
I use .then in my Code. But nothing happens. It never entered .then since I added it.

**Comment by jleeson** [comment]
Can you provide a minimal reproduction? Additionally does the PR you submitted resolve the problem? As i mentioned the code is functionally equivalent so if for some reason the load function is not resolving after the server restoration is complete, it likely a deeper issue.

**Comment by jleeson** [comment]
@Phyroks I went ahead and tested both async/await and .then with the backup.load function using the latest version of this package and its working correctly.

**Using await**
```js
const backupData = await backup.fetch(backupId);

await backup.load(backupData.data, message.guild, { maxMessagesPerChannel: 250, speed: 1500 });
await message.author.send(":white_check_mark: | Backup restored successfully!");
```

**Using .then**
```js
const backupData = await backup.fetch(backupId);

backup.load(backupData.data, message.guild, { maxMessagesPerChannel: 250, speed: 1500 })
.then(() => message.author.send(":white_check_mark: | Backup restored successfully!"));
```

Are you getting any specific errors? does the backup fully load but the promise never resolves? If you can provide some more information or a code snippet to indicate where the problem may originate Im happy to take a look. In the future you can always first create an issue and I can help you determine if its a bug in the package or not before submitted a PR.

**Comment by Phyroks** [comment]
In my case
```
BackupHandler.load(backupData, interaction.guild, {
    clearGuildBeforeRestore: true
}).then(() => {
    //TODO @Luca Schau dir diese Promise mal an


    console.log("Resolved Promise")

    TaskManager.deleteTask(task, interaction.client)

    interaction.guild.channels.cache.filter((channel) => channel.type === 'GUILD_TEXT').first().then(async (channel) => {
        console.log(channel)
        let finishedEmbed = new EmbedBuilder(interaction.guild.id, interaction.client)
        finishedEmbed.setTitle("Fertig!")
        finishedEmbed.setDescription("Tada!")
        channel.send({embeds: [await finishedEmbed.build()]})
    })
}).catch((error) => {
    ErrorHandler.handleThrowable(error)
})
```

It never resolved the promise

**Comment by jleeson** [comment]
@Phyroks can you show me the function definition for BackupHandler.load? it looks like its a wrapper over the load function defined in this package. Additionally have you confirmed that the code you submitted in this PR resolves the problem for you?

**Comment by jleeson** [comment]
Last thing to help me figure out whats doing on, How is backupData being defined?

**Comment by jleeson** [comment]
After testing the load promise multiple times in different ways, Im fairly confident this is not a problem with the package itself and the PR submits functionally equivalent code as well as introduces a few minor bugs through an unintended import and throwing errors without promise rejection. As such I am going to close this PR for now.

If you can confirm this PR does solve the problem you are having, I am happy to reopen the PR and take a deeper look and see whats causing the promise to never resolve. Otherwise if you are still having problems feel free to open a new issue and I can help you get it working.

**Pull request closed without merging**
